### ISSUE TITLE
migrating from Foxy to galactic

### ISSUE THREAD

**Issue by HusamZain** [Factor-Robotics/odrive_ros2_control#11]
thank you for your contribution.

I'm using ros2 galactic, and trying to use your lib.
but when I try to build the package, I got
![Screenshot from 2022-03-12 12-34-12](https://user-images.githubusercontent.com/97671800/158016418-0b9a1450-4339-40c5-a3f0-04247e524e79.png)
 so I tried to migrate it to galactic as mentioned [here](https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/doc/hardware_components_userdoc.rst) in ros2-conttrol framework.
 this is the [package](https://github.com/HusamZain/Odrive_ros2_control_galactic/tree/main/odrive_ros2_control/odrive_hardware_interface) after editing according to the ros2-control migration document,
but I got this error
![Screenshot from 2022-03-13 18-37-24](https://user-images.githubusercontent.com/97671800/158072618-855a4d9a-b04f-4c98-a983-51ea796e70ea.png)

I'm knew to programming and couldn't solve it, do you have any idea how to solve it?

**Comment by borongyuan** [comment]
Hi,

I see that there are some changes in the interface. Actually lifecycle node is indeed a better choice for managing hardware, which is a generic abstraction. I have tried it when implementing other drivers. Since it has not been introduced to the foxy branch of ros2_control, we won't update odrive_hardware_interface for this. We currently only intend to support LTS releases of ROS2. So we'll skip Galactic and look forward to Humble. If you have finished this part of migration, contributions are welcomed.
For your current issue, it seems all the return_type should be replaced by CallbackReturn. From your screenshot, it looks like return_type is still being used somewhere in the code.

Thanks

**Comment by HusamZain** [comment]
@borongyuan thank you for your replay.
yes and I changed all the return_type that was proposed in the documentation (configure, active ,deactive), but wasn't sure about the 'prepare_command_mode_switch', and if I do change it I got this error, sorry for the inconvenient 
![Screenshot from 2022-03-14 09-19-05](https://user-images.githubusercontent.com/97671800/158132344-190f9caf-5a5a-4d81-aaea-1caa98c11744.png)
any suggestion how could I solve it?

**Comment by borongyuan** [comment]
In [this file](https://github.com/ros-controls/ros2_control/blob/galactic/hardware_interface/include/hardware_interface/system_interface.hpp) both return_type and CallbackReturn are used. I just glanced at the code but don't know why. Anyway, this is the base class so we should have the same declaration.
